### ISSUE TITLE
Not updated and having bugs that are fixed in the official

### ISSUE THREAD

**Issue by Vortelf** [sbolel/panolens.js#2]
Either update it or remove it from npm database.
Better make the original a dep on your 'pano' than this fork.

**Comment by sbolel** [comment]
I agree, I'll remove it from the database and make the original the dependency. Thanks for pointing that out!

**Comment by sbolel** [comment]
@Vortelf I tried to unpublish the package from npm but I got the following error:

```
$ npm unpublish --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! unpublish Failed to update data
npm ERR! code E500
npm ERR! You can no longer unpublish this version.
npm ERR! Please deprecate it instead:
```

I've marked every version of the package as deprecated, linking to pchen66/panolens.js in the message. I've also dropped the package version to `0.0.0`, and marked the package as deprecated in package.json. I've updated the README to point to the original project as well, and pushed v0.0.0 to npm with the updated README and deprecated flag in package.json.

The [docs](https://docs.npmjs.com/cli/unpublish) note that,

> With the default registry (registry.npmjs.org), unpublish is only allowed with versions published in the last 24 hours. If you are trying to unpublish a version published longer ago than that, contact support@npmjs.com. 

If needed, I'm happy to contact them. If @pchen66 would like to take ownership of the package on npmjs.org, I'm happy to transfer it over. I apologize for the confusion! Thank you for calling this out.

**Comment by sbolel** [comment]
The [docs](https://docs.npmjs.com/cli/unpublish) note that,

> With the default registry (registry.npmjs.org), unpublish is only allowed with versions published in the last 24 hours. If you are trying to unpublish a version published longer ago than that, contact support@npmjs.com.

If needed, I'm happy to contact them.
